"""Add profile 

Revision ID: ba729382264e
Revises: 34cb374c5b11
Create Date: 2024-06-10 03:35:02.295337

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba729382264e"
down_revision: Union[str, None] = "34cb374c5b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "profiles", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "profiles", type_="unique")
    # ### end Alembic commands ###
