"""qwerty

Revision ID: 1f345f777c65
Revises: cd2effbb119a
Create Date: 2024-06-13 05:02:58.956212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f345f777c65"
down_revision: Union[str, None] = "cd2effbb119a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint("OrderUserID", "orders", ["user_id"])
    op.create_foreign_key("OrderUserIDforegn", "orders", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("OrderUserIDforegn", "orders", type_="foreignkey")
    op.drop_constraint("OrderUserID", "orders", type_="unique")
    op.drop_column("orders", "user_id")
    # ### end Alembic commands ###
