"""add shortname to product

Revision ID: f59f791feed8
Revises: d69817748188
Create Date: 2024-07-24 23:01:58.510970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f59f791feed8"
down_revision: Union[str, None] = "d69817748188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("shortname", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "shortname")
    # ### end Alembic commands ###
