"""delete promocode order(cart)

Revision ID: c23d8a8c7ae2
Revises: 1f345f777c65
Create Date: 2024-06-13 06:57:47.769558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c23d8a8c7ae2"
down_revision: Union[str, None] = "1f345f777c65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "promocode")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "promocode", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
