"""Add email to user

Revision ID: 34cb374c5b11
Revises: 24fc51753fcc
Create Date: 2024-06-10 00:32:42.174894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34cb374c5b11"
down_revision: Union[str, None] = "24fc51753fcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=64), nullable=False))
    op.create_unique_constraint("usermail", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("usermail", "users", type_="unique")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
