"""Add quantity to product

Revision ID: 24fc51753fcc
Revises: 98b0ab52affe
Create Date: 2024-06-09 21:42:25.294651

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24fc51753fcc"
down_revision: Union[str, None] = "98b0ab52affe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("quantity", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "profiles",
        "bio",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "bio",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("products", "quantity")
    # ### end Alembic commands ###
