"""fixed unique username

Revision ID: cec027fe3b8e
Revises: 79972395c2d0
Create Date: 2024-06-10 19:40:36.114223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cec027fe3b8e"
down_revision: Union[str, None] = "79972395c2d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
