"""add type and battery to product

Revision ID: 7f3735bca6d5
Revises: f59f791feed8
Create Date: 2024-07-24 23:05:18.016757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f3735bca6d5"
down_revision: Union[str, None] = "f59f791feed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("type", sa.String(), nullable=False))
    op.add_column(
        "products", sa.Column("battery", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "battery")
    op.drop_column("products", "type")
    # ### end Alembic commands ###
