"""Add password to user table

Revision ID: 79972395c2d0
Revises: ba729382264e
Create Date: 2024-06-10 19:22:24.070218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79972395c2d0"
down_revision: Union[str, None] = "ba729382264e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password", sa.String(length=128), nullable=False)
    )
    op.add_column("users", sa.Column("active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
